title: "UNL Lunabotics Documentation"
email: "your-email@example.com"
description: "Your site description"
baseurl: "" 
url: "" 

# Use the Basically Basic theme
remote_theme: "mmistakes/jekyll-theme-basically-basic"

plugins:
  - jekyll-feed
  - jekyll-remote-theme