title: UNL Lunabotics Documentation
description: Documentation for the UNL-Lunabotics RSO
theme: just-the-docs

url: https://unl-lunabotics.github.io

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

color_scheme: light

favicon: favicon.ico

aux_links:
  "Toggle Light/Dark Theme":
    - "javascript:toggleTheme()"
  "UNL-Lunabotics on GitHub":
    - "//github.com/unl-lunabotics"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/unl-lunabotics/unl-lunabotics.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

callouts_level: loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red